# vim:fileencoding=utf-8:foldmethod=marker

# theme
include current-theme.conf

# font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.5

# background
background_opacity 0.95
dynamic_background_opacity yes

# cursor 
cursor none
cursor_text_color background
cursor_shape block
shell_integration no-cursor
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# tab bar
tab_bar_edge top
tab_bar_style fade

# ssh
term xterm-256color

# window
hide_window_decorations yes

# smart splits integration
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right

# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+l

# the 3 here is the resize amount, adjust as needed
map alt+j kitten relative_resize.py down  3
map alt+k kitten relative_resize.py up    3
map alt+h kitten relative_resize.py left  3
map alt+l kitten relative_resize.py right 3

map --when-focus-on var:IS_NVIM alt+j
map --when-focus-on var:IS_NVIM alt+k
map --when-focus-on var:IS_NVIM alt+h
map --when-focus-on var:IS_NVIM alt+l

allow_remote_control yes
listen_on unix:/tmp/mykitty
