# vim:fileencoding=utf-8:foldmethod=marker

# theme
include current-theme.conf

# font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.5

# background
background_opacity 0.95
dynamic_background_opacity yes

# cursor 
cursor none
cursor_text_color background
cursor_shape block
shell_integration no-cursor
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# tab bar
tab_bar_edge top
tab_bar_style fade

# ssh
term xterm-256color
